[tool.poetry]
name = "django_kt_template_by_k_tech"
version = "0.1.0"
description = "Django KT template by K-Tech"
authors = ["G.Bronzini"]
packages = [
    { include = "django_kt_template_by_k_tech", from="src" },
]

[tool.poetry.scripts]
django_kt_template_by_k_tech = 'django_kt_template_by_k_tech.cli:main'


[tool.poetry.dependencies]
python = "^3.9"
Django = "==4.2"
django-click = "*"
django-environ = "*"
django-regex = "*"
sentry-sdk = "*"
uwsgi = "*"
celery = "^5.1.2"
django-celery-beat = "^2.2.1"
django-strategy-field = "*"
django-extensions = "*"
django-database-for-apps = "*"
psycopg2-binary = "*"
djangorestframework = "^3.15.2"
selenium = "^4.26.1"
webdriver-manager = "^4.0.2"
factory-boy = "^3.3.1"
django-cors-headers = "^4.6.0"
python-dotenv = "^1.0.1"

[tool.poetry.dev-dependencies]
bumpversion = "*"
flake8 = "*"
ipython = "*"
isort = "*"
pre-commit = "*"
pytest = "*"
pytest-coverage = "*"
pytest-django = "*"
pytest-echo = "*"
pytest-pythonpath = "*"
pytest-env = "*"
tox = "*"
django-debug-toolbar = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
