site_name: "{{ cookiecutter.project_name }}"
site_description: "{{ cookiecutter.description }}"
docs_dir: docs
site_dir: ~build/docs
dev_addr: 127.0.0.1:8001
strict: false

theme:
  name: material
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - tables
  - toc:
      permalink: "#"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - Commands: command.md