[pytest]
# django_debug_mode = true
env =
    {{ cookiecutter.environ__prefix }}_SECRET_ENCRYPTION_KEY=st6Fax93zkaupsqIUQb8h5RJmMBGggk8ZooBjVV7
    DJANGO_SETTINGS_MODULE={{ cookiecutter.project__module }}.config.settings
norecursedirs = data _plugin_template ~* .* node_modules
pythonpath =
    ./src
    ./tests/_extras
django_find_project = false